Add configure test for ncurses

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -94,6 +94,17 @@ int main(void) {
 }
 EOF
 
+echo -n "Testing for ncurses"
+comp_cmd="cc conftest.c -lncurses -o conftest.exe"
+if (eval "$comp_cmd") 2> contest.err; then
+    echo "   "yes
+else
+    echo "   "not found
+    echo "Please install ncurses developement library and try again"
+    exit 1
+fi
+rm -f conftest.exe
+
 echo -n "Testing if compiler recognizes -no-pie"
 NO_PIE_OPT=-no-pie
 comp_cmd="cc $NO_PIE_OPT conftest.c -o conftest.exe"
