Add test for missing corepop

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47,6 +47,11 @@ while [ "$*" != "" ] ; do
     shift
 done
 
+if [ ! -f $POP_target/pop/corepop ] ; then
+    echo "corepop is missing in target tree"
+    exit 1
+fi
+
 if [ -d pop/packages -a -d pop/packages/neural -a \
      -d pop/packages/popvision ] ; then
         PACK_CONF=yes
